# https://github.com/aws/serverless-application-model/issues/1553

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Updates any non OPTIONS method for an API gateway to require an API key

Parameters:
  ApiIds:
    Type: CommaDelimitedList
  StageName:
    Type: String
    Description: The api gateway stage name

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256

Resources:
  EnableApiKeysForMethodsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Updates any non OPTIONS method for an API gateway to require an API key
      Handler: src/main.handler
      Policies:
        - Statement:
            - Sid: ModifyApiGatewayPolicy
              Effect: Allow
              Action:
                - apigateway:*
              Resource: '*'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        OutExtension:
          - .js=.mjs
        Target: 'es2020'
        Sourcemap: false
        EntryPoints:
          - src/main.js
        External:
          - '@aws-sdk'
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

  EnableApiKeysForMethodsResource:
    Type: Custom::EnableApiKeysForMethods
    Properties:
      ServiceToken: !GetAtt [EnableApiKeysForMethodsFunction, Arn]
      ApiIds: !Ref ApiIds
      StageName: !Ref StageName

Metadata:
  AWS::ServerlessRepo::Application:
    Name: firstcoders-custom-cf-resource-require-key-for-methods
    Description: >
      AWS SAM has severe issues with parameterising the ApiKeyRequired property. This custom cloudformation resource will update any non-OPTIONS request method to set it to require an API key.
    Author: Team First Coders
    ReadmeUrl: README.md
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE.txt
    Labels: ['layer', 'lambda', 'serverless', 'cloudformation']
    HomePageUrl: https://github.com/sound-ws/custom-cf-resource-require-key-for-methods
    SourceCodeUrl: https://github.com/sound-ws/custom-cf-resource-require-key-for-methods
    SemanticVersion: 1.0.0 # overwritten by sam publish cli command
